server:
  port: 9192

spring:
  application:
    name: gateway2
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: service_url
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - name: Logging

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


